#----------------------
# Configuration file for compilation
#
#  Once in the file, do not change the order
#
# Directory | has C/C++ | has SQL | has DOC
#----------------------
#----------------------
# common must be first can not be removed
#----------------------
common              | Y | Y | N
#----------------------
# dijkstra can not be removed
#   Has the command needed to link with prostgresl
#----------------------
dijkstra            | Y | Y | Y
allpairs            | N | Y | Y
astar               | N | Y | Y
driving_distance    | N | Y | Y
ksp                 | N | Y | Y
tsp                 | N | Y | Y
alpha_shape         | Y | Y | Y
bdAstar             | N | Y | Y
bdDijkstra          | N | Y | Y
trsp                | N | Y | Y
max_flow            | N | Y | Y
contraction         | N | Y | Y
pickDeliver         | N | Y | Y
vrp_basic           | N | Y | Y
withPoints          | N | Y | Y
lineGraph           | N | Y | Y
components          | N | Y | Y
bellman_ford        | N | Y | Y
cpp_common          | Y | N | N
dagShortestPath     | N | Y | Y
chinese             | N | Y | Y
spanningTree        | N | Y | Y
mincut              | N | Y | Y
version             | N | Y | Y
topologicalSort     | N | Y | Y
transitiveClosure   | N | Y | Y
breadthFirstSearch  | N | Y | Y
#----------------------
# SQL only directories
#----------------------
topology            | N | Y | Y
deprecated          | N | Y | N
