#!/usr/bin/perl -w

%main::tests = (
    'any' => {
        'files' => [qw(
            sequentialVertexColoring.pg
            doc-bipartite
            doc-edgeColoring
            )]
    },

);

1;
