#!/usr/bin/perl -w

%main::tests = (
    'any' => {
        'comment' => 'LineGrpah test for any versions.',
        'data' => [ ],
        'tests' => [qw(
            pgtap_design
            mathw_1
            mathw_2
            wiki_1
            )],
        'documentation' => [qw(
            pgtap_design
            mathw_1
            mathw_2
            wiki_1
            )]
    },

);

1;
