#!/usr/bin/perl -w

%main::tests = (
    'any' => {
        'comment' => 'LineGrpah test for any versions.',
        'data' => [ ],
        'tests' => [qw(
            doc-pgr_lineGraphFull
            doc-pgr_lineGraph
            pgtap_design_lineGraphFull
            pgtap_design
            proofOfConcept1
            proofOfConcept2
            mathw_1
            mathw_2
            wiki_1
            )],
        'documentation' => [qw(
            doc-pgr_lineGraphFull
            doc-pgr_lineGraph
            )]
    },

);

1;
