#!/usr/bin/perl -w

%main::tests = (
    'any' => {
        'files' => [qw(
            issue900
            createVertTab-any
            createTopology.pg
            createVerticesTable.pg
            analyzeGraph.pg
            analyzeOneWay.pg
            nodeNetwork.pg
            extractVertices.pg
            degree
            )],
    },
);

1;
