#!/usr/bin/perl -w

%main::tests = (
    'any' => {
        'tests' => [qw(
            johnson.pg
            floydWarshall.pg
            )],

        'files' => [qw(
            johnson.pg
            floydWarshall.pg
            )]
    },
);

1;
