#!/usr/bin/perl -w

%main::tests = (
    'any' => {
        'comment' => 'All pairs tests.',
        'data' => [''],
        'tests' => [qw(
            johnson.pg
            floydWarshall.pg
            )],

        'documentation' => [qw(
            johnson.pg
            floydWarshall.pg
            )]
    },
);

1;
