name: Check files

# Makes a general check on the files
# Verifies:
# - the signatures are up-to-date
# - the release_notes and NEWS are consitent
# - the files have a license
# - the shell scripts are ok

on:
  push:
  pull_request:

jobs:
  Signature_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Signatures are not removed
        run: |
          tools/scripts/test_signatures.sh

  News_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: News file up to date
        run: |
          tools/release-scripts/notes2news.pl
          if git status | grep 'NEWS'; then echo "NEWS is not up to date"; exit 1; fi
          if ! grep -q $(grep -Po '(?<=project\(PGROUTING VERSION )[^;]+' CMakeLists.txt) NEWS; then echo "Missing section in NEWS"; exit 1; fi

  License_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Requirements
        run: |
          sudo apt install -y licensecheck
      - name: Run License Check
        run: ./tools/scripts/test_license.sh

  Shell_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Requirements
        run: |
          sudo apt install -y shellcheck
      - name: Run Shell Check
        run: ./tools/scripts/test_shell.sh
